import { ICard } from '@models';

export const DECK: ICard[] = [
  {
    id: 1,
    visibleValue: 'A',
    color: 'red',
    suitIcon: '♦',
    suitName: 'diamonds',
    rateValue: 1,
  },
  {
    id: 2,
    visibleValue: '2',
    color: 'red',
    suitIcon: '♦',
    suitName: 'diamonds',
    rateValue: 2,
  },
  {
    id: 3,
    visibleValue: '3',
    color: 'red',
    suitIcon: '♦',
    suitName: 'diamonds',
    rateValue: 3,
  },
  {
    id: 4,
    visibleValue: '4',
    color: 'red',
    suitIcon: '♦',
    suitName: 'diamonds',
    rateValue: 4,
  },
  {
    id: 5,
    visibleValue: '5',
    color: 'red',
    suitIcon: '♦',
    suitName: 'diamonds',
    rateValue: 5,
  },
  {
    id: 6,
    visibleValue: '6',
    color: 'red',
    suitIcon: '♦',
    suitName: 'diamonds',
    rateValue: 6,
  },
  {
    id: 7,
    visibleValue: '7',
    color: 'red',
    suitIcon: '♦',
    suitName: 'diamonds',
    rateValue: 7,
  },
  {
    id: 8,
    visibleValue: '8',
    color: 'red',
    suitIcon: '♦',
    suitName: 'diamonds',
    rateValue: 8,
  },
  {
    id: 9,
    visibleValue: '9',
    color: 'red',
    suitIcon: '♦',
    suitName: 'diamonds',
    rateValue: 9,
  },
  {
    id: 10,
    visibleValue: '10',
    color: 'red',
    suitIcon: '♦',
    suitName: 'diamonds',
    rateValue: 10,
  },
  {
    id: 11,
    visibleValue: 'J',
    color: 'red',
    suitIcon: '♦',
    suitName: 'diamonds',
    rateValue: 11,
  },
  {
    id: 12,
    visibleValue: 'Q',
    color: 'red',
    suitIcon: '♦',
    suitName: 'diamonds',
    rateValue: 12,
  },
  {
    id: 13,
    visibleValue: 'K',
    color: 'red',
    suitIcon: '♦',
    suitName: 'diamonds',
    rateValue: 13,
  },
  {
    id: 14,
    visibleValue: 'A',
    color: 'black',
    suitIcon: '♣',
    suitName: 'clubs',
    rateValue: 1,
  },
  {
    id: 15,
    visibleValue: '2',
    color: 'black',
    suitIcon: '♣',
    suitName: 'clubs',
    rateValue: 2,
  },
  {
    id: 16,
    visibleValue: '3',
    color: 'black',
    suitIcon: '♣',
    suitName: 'clubs',
    rateValue: 3,
  },
  {
    id: 17,
    visibleValue: '4',
    color: 'black',
    suitIcon: '♣',
    suitName: 'clubs',
    rateValue: 4,
  },
  {
    id: 18,
    visibleValue: '5',
    color: 'black',
    suitIcon: '♣',
    suitName: 'clubs',
    rateValue: 5,
  },
  {
    id: 19,
    visibleValue: '6',
    color: 'black',
    suitIcon: '♣',
    suitName: 'clubs',
    rateValue: 6,
  },
  {
    id: 20,
    visibleValue: '7',
    color: 'black',
    suitIcon: '♣',
    suitName: 'clubs',
    rateValue: 7,
  },
  {
    id: 21,
    visibleValue: '8',
    color: 'black',
    suitIcon: '♣',
    suitName: 'clubs',
    rateValue: 8,
  },
  {
    id: 22,
    visibleValue: '9',
    color: 'black',
    suitIcon: '♣',
    suitName: 'clubs',
    rateValue: 9,
  },
  {
    id: 23,
    visibleValue: '10',
    color: 'black',
    suitIcon: '♣',
    suitName: 'clubs',
    rateValue: 10,
  },
  {
    id: 24,
    visibleValue: 'J',
    color: 'black',
    suitIcon: '♣',
    suitName: 'clubs',
    rateValue: 11,
  },
  {
    id: 25,
    visibleValue: 'Q',
    color: 'black',
    suitIcon: '♣',
    suitName: 'clubs',
    rateValue: 12,
  },
  {
    id: 26,
    visibleValue: 'K',
    color: 'black',
    suitIcon: '♣',
    suitName: 'clubs',
    rateValue: 13,
  },
  {
    id: 27,
    visibleValue: 'A',
    color: 'red',
    suitIcon: '♥',
    suitName: 'hearts',
    rateValue: 1,
  },
  {
    id: 28,
    visibleValue: '2',
    color: 'red',
    suitIcon: '♥',
    suitName: 'hearts',
    rateValue: 2,
  },
  {
    id: 29,
    visibleValue: '3',
    color: 'red',
    suitIcon: '♥',
    suitName: 'hearts',
    rateValue: 3,
  },
  {
    id: 30,
    visibleValue: '4',
    color: 'red',
    suitIcon: '♥',
    suitName: 'hearts',
    rateValue: 4,
  },
  {
    id: 31,
    visibleValue: '5',
    color: 'red',
    suitIcon: '♥',
    suitName: 'hearts',
    rateValue: 5,
  },
  {
    id: 32,
    visibleValue: '6',
    color: 'red',
    suitIcon: '♥',
    suitName: 'hearts',
    rateValue: 6,
  },
  {
    id: 33,
    visibleValue: '7',
    color: 'red',
    suitIcon: '♥',
    suitName: 'hearts',
    rateValue: 7,
  },
  {
    id: 34,
    visibleValue: '8',
    color: 'red',
    suitIcon: '♥',
    suitName: 'hearts',
    rateValue: 8,
  },
  {
    id: 35,
    visibleValue: '9',
    color: 'red',
    suitIcon: '♥',
    suitName: 'hearts',
    rateValue: 9,
  },
  {
    id: 36,
    visibleValue: '10',
    color: 'red',
    suitIcon: '♥',
    suitName: 'hearts',
    rateValue: 10,
  },
  {
    id: 37,
    visibleValue: 'J',
    color: 'red',
    suitIcon: '♥',
    suitName: 'hearts',
    rateValue: 11,
  },
  {
    id: 38,
    visibleValue: 'Q',
    color: 'red',
    suitIcon: '♥',
    suitName: 'hearts',
    rateValue: 12,
  },
  {
    id: 39,
    visibleValue: 'K',
    color: 'red',
    suitIcon: '♥',
    suitName: 'hearts',
    rateValue: 13,
  },
  {
    id: 40,
    visibleValue: 'A',
    color: 'black',
    suitIcon: '♠',
    suitName: 'spades',
    rateValue: 1,
  },
  {
    id: 41,
    visibleValue: '2',
    color: 'black',
    suitIcon: '♠',
    suitName: 'spades',
    rateValue: 2,
  },
  {
    id: 42,
    visibleValue: '3',
    color: 'black',
    suitIcon: '♠',
    suitName: 'spades',
    rateValue: 3,
  },
  {
    id: 43,
    visibleValue: '4',
    color: 'black',
    suitIcon: '♠',
    suitName: 'spades',
    rateValue: 4,
  },
  {
    id: 44,
    visibleValue: '5',
    color: 'black',
    suitIcon: '♠',
    suitName: 'spades',
    rateValue: 5,
  },
  {
    id: 45,
    visibleValue: '6',
    color: 'black',
    suitIcon: '♠',
    suitName: 'spades',
    rateValue: 6,
  },
  {
    id: 46,
    visibleValue: '7',
    color: 'black',
    suitIcon: '♠',
    suitName: 'spades',
    rateValue: 7,
  },
  {
    id: 47,
    visibleValue: '8',
    color: 'black',
    suitIcon: '♠',
    suitName: 'spades',
    rateValue: 8,
  },
  {
    id: 48,
    visibleValue: '9',
    color: 'black',
    suitIcon: '♠',
    suitName: 'spades',
    rateValue: 9,
  },
  {
    id: 49,
    visibleValue: '10',
    color: 'black',
    suitIcon: '♠',
    suitName: 'spades',
    rateValue: 10,
  },
  {
    id: 50,
    visibleValue: 'J',
    color: 'black',
    suitIcon: '♠',
    suitName: 'spades',
    rateValue: 11,
  },
  {
    id: 51,
    visibleValue: 'Q',
    color: 'black',
    suitIcon: '♠',
    suitName: 'spades',
    rateValue: 12,
  },
  {
    id: 52,
    visibleValue: 'K',
    color: 'black',
    suitIcon: '♠',
    suitName: 'spades',
    rateValue: 13,
  },
  {
    id: 53,
    visibleValue: 'joker',
    color: 'red',
    suitIcon: 'joker',
    suitName: 'joker',
    rateValue: 15,
  },
  {
    id: 54,
    visibleValue: 'joker',
    color: 'black',
    suitIcon: 'joker',
    suitName: 'joker',
    rateValue: 15,
  },
];
