name: PR Checks and SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  prevent_author_merge:
    name: Block PR Author Merge
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR author is merging
        run: |
          PR_AUTHOR=$(jq -r ".pull_request.user.login" "$GITHUB_EVENT_PATH")
          if [ "$PR_AUTHOR" == "$GITHUB_ACTOR" ]; then
            echo "O autor do PR não pode fazer merge!"
            exit 1
          fi

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage report
        run: npm run test:coverage

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=pd-frontend
            -Dsonar.organization=president-card-game
            -Dsonar.sources=src
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
